name: instagram_media_picker
description: Fetches a Instagram users images, and allows them to select images.
version: 0.0.11
homepage: https://github.com/augustkimo/instagram_media_picker

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.3
  flutter_webview_plugin: ^0.4.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
